version: '3.7'

services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - '55432:5432'
    environment:
      - POSTGRESQL_USER=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DB=next-saas